//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praxedo_Send_Attachment_DEV.AttachmentManager {
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(operationResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(entitiesRequestResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(attachmentsRequestResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(attachmentContentOperationResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.praxedo.com/v6/businessEvent")]
    public partial class simpleOperationResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private int resultCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
                this.RaisePropertyChanged("resultCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(extendedAttachment))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.praxedo.com/v6/businessEvent")]
    public partial class attachment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string entityIdField;
        
        private wsValuedEntry[] extensionsField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string entityId {
            get {
                return this.entityIdField;
            }
            set {
                this.entityIdField = value;
                this.RaisePropertyChanged("entityId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("extensions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public wsValuedEntry[] extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
                this.RaisePropertyChanged("extensions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.praxedo.com/v6/businessEvent")]
    public partial class wsValuedEntry : wsEntry {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(wsValuedEntry))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.praxedo.com/v6/businessEvent")]
    public partial class wsEntry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.praxedo.com/v6/businessEvent")]
    public partial class extendedAttachment : attachment {
        
        private bool addedOnDeviceField;
        
        private System.DateTime creationDateField;
        
        private bool creationDateFieldSpecified;
        
        private string descriptionField;
        
        private bool externalField;
        
        private string idField;
        
        private System.DateTime lastModificationDateField;
        
        private bool lastModificationDateFieldSpecified;
        
        private int sizeField;
        
        private bool sizeFieldSpecified;
        
        private bool unmodifiableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool addedOnDevice {
            get {
                return this.addedOnDeviceField;
            }
            set {
                this.addedOnDeviceField = value;
                this.RaisePropertyChanged("addedOnDevice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime creationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
                this.RaisePropertyChanged("creationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool creationDateSpecified {
            get {
                return this.creationDateFieldSpecified;
            }
            set {
                this.creationDateFieldSpecified = value;
                this.RaisePropertyChanged("creationDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool external {
            get {
                return this.externalField;
            }
            set {
                this.externalField = value;
                this.RaisePropertyChanged("external");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime lastModificationDate {
            get {
                return this.lastModificationDateField;
            }
            set {
                this.lastModificationDateField = value;
                this.RaisePropertyChanged("lastModificationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastModificationDateSpecified {
            get {
                return this.lastModificationDateFieldSpecified;
            }
            set {
                this.lastModificationDateFieldSpecified = value;
                this.RaisePropertyChanged("lastModificationDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
                this.RaisePropertyChanged("size");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sizeSpecified {
            get {
                return this.sizeFieldSpecified;
            }
            set {
                this.sizeFieldSpecified = value;
                this.RaisePropertyChanged("sizeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public bool unmodifiable {
            get {
                return this.unmodifiableField;
            }
            set {
                this.unmodifiableField = value;
                this.RaisePropertyChanged("unmodifiable");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(entitiesRequestResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(attachmentsRequestResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(attachmentContentOperationResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.praxedo.com/v6/businessEvent")]
    public partial class operationResult : simpleOperationResult {
        
        private simpleOperationResult[] warningsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("warnings", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public simpleOperationResult[] warnings {
            get {
                return this.warningsField;
            }
            set {
                this.warningsField = value;
                this.RaisePropertyChanged("warnings");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(attachmentsRequestResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.praxedo.com/v6/businessEvent")]
    public abstract partial class entitiesRequestResult : operationResult {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.praxedo.com/v6/businessEvent")]
    public partial class attachmentsRequestResult : entitiesRequestResult {
        
        private extendedAttachment[] entitiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("entities", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public extendedAttachment[] entities {
            get {
                return this.entitiesField;
            }
            set {
                this.entitiesField = value;
                this.RaisePropertyChanged("entities");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.praxedo.com/v6/businessEvent")]
    public partial class attachmentContentOperationResult : operationResult {
        
        private byte[] contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.praxedo.com/v6/businessEvent", ConfigurationName="AttachmentManager.BusinessEventAttachmentManager")]
    public interface BusinessEventAttachmentManager {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="getAttachmentContent", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Praxedo_Send_Attachment_DEV.AttachmentManager.simpleOperationResult), Action="getAttachmentContent", Name="WSFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(attachment))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Praxedo_Send_Attachment_DEV.AttachmentManager.getAttachmentContentResponse getAttachmentContent(Praxedo_Send_Attachment_DEV.AttachmentManager.getAttachmentContent request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getAttachmentContent", ReplyAction="*")]
        System.Threading.Tasks.Task<Praxedo_Send_Attachment_DEV.AttachmentManager.getAttachmentContentResponse> getAttachmentContentAsync(Praxedo_Send_Attachment_DEV.AttachmentManager.getAttachmentContent request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="deleteAttachment", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Praxedo_Send_Attachment_DEV.AttachmentManager.simpleOperationResult), Action="deleteAttachment", Name="WSFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(attachment))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Praxedo_Send_Attachment_DEV.AttachmentManager.deleteAttachmentResponse deleteAttachment(Praxedo_Send_Attachment_DEV.AttachmentManager.deleteAttachment request);
        
        [System.ServiceModel.OperationContractAttribute(Action="deleteAttachment", ReplyAction="*")]
        System.Threading.Tasks.Task<Praxedo_Send_Attachment_DEV.AttachmentManager.deleteAttachmentResponse> deleteAttachmentAsync(Praxedo_Send_Attachment_DEV.AttachmentManager.deleteAttachment request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="listAttachments", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Praxedo_Send_Attachment_DEV.AttachmentManager.simpleOperationResult), Action="listAttachments", Name="WSFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(attachment))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Praxedo_Send_Attachment_DEV.AttachmentManager.listAttachmentsResponse listAttachments(Praxedo_Send_Attachment_DEV.AttachmentManager.listAttachments request);
        
        [System.ServiceModel.OperationContractAttribute(Action="listAttachments", ReplyAction="*")]
        System.Threading.Tasks.Task<Praxedo_Send_Attachment_DEV.AttachmentManager.listAttachmentsResponse> listAttachmentsAsync(Praxedo_Send_Attachment_DEV.AttachmentManager.listAttachments request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="createAttachment", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Praxedo_Send_Attachment_DEV.AttachmentManager.simpleOperationResult), Action="createAttachment", Name="WSFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(attachment))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Praxedo_Send_Attachment_DEV.AttachmentManager.createAttachmentResponse createAttachment(Praxedo_Send_Attachment_DEV.AttachmentManager.createAttachment request);
        
        [System.ServiceModel.OperationContractAttribute(Action="createAttachment", ReplyAction="*")]
        System.Threading.Tasks.Task<Praxedo_Send_Attachment_DEV.AttachmentManager.createAttachmentResponse> createAttachmentAsync(Praxedo_Send_Attachment_DEV.AttachmentManager.createAttachment request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAttachmentContent", WrapperNamespace="http://ws.praxedo.com/v6/businessEvent", IsWrapped=true)]
    public partial class getAttachmentContent {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.praxedo.com/v6/businessEvent", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string attachmentId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.praxedo.com/v6/businessEvent", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("options", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Praxedo_Send_Attachment_DEV.AttachmentManager.wsEntry[] options;
        
        public getAttachmentContent() {
        }
        
        public getAttachmentContent(string attachmentId, Praxedo_Send_Attachment_DEV.AttachmentManager.wsEntry[] options) {
            this.attachmentId = attachmentId;
            this.options = options;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAttachmentContentResponse", WrapperNamespace="http://ws.praxedo.com/v6/businessEvent", IsWrapped=true)]
    public partial class getAttachmentContentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.praxedo.com/v6/businessEvent", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Praxedo_Send_Attachment_DEV.AttachmentManager.attachmentContentOperationResult @return;
        
        public getAttachmentContentResponse() {
        }
        
        public getAttachmentContentResponse(Praxedo_Send_Attachment_DEV.AttachmentManager.attachmentContentOperationResult @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteAttachment", WrapperNamespace="http://ws.praxedo.com/v6/businessEvent", IsWrapped=true)]
    public partial class deleteAttachment {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.praxedo.com/v6/businessEvent", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Praxedo_Send_Attachment_DEV.AttachmentManager.attachment attachment;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.praxedo.com/v6/businessEvent", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("options", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Praxedo_Send_Attachment_DEV.AttachmentManager.wsEntry[] options;
        
        public deleteAttachment() {
        }
        
        public deleteAttachment(Praxedo_Send_Attachment_DEV.AttachmentManager.attachment attachment, Praxedo_Send_Attachment_DEV.AttachmentManager.wsEntry[] options) {
            this.attachment = attachment;
            this.options = options;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteAttachmentResponse", WrapperNamespace="http://ws.praxedo.com/v6/businessEvent", IsWrapped=true)]
    public partial class deleteAttachmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.praxedo.com/v6/businessEvent", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Praxedo_Send_Attachment_DEV.AttachmentManager.operationResult @return;
        
        public deleteAttachmentResponse() {
        }
        
        public deleteAttachmentResponse(Praxedo_Send_Attachment_DEV.AttachmentManager.operationResult @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listAttachments", WrapperNamespace="http://ws.praxedo.com/v6/businessEvent", IsWrapped=true)]
    public partial class listAttachments {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.praxedo.com/v6/businessEvent", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string businessEventId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.praxedo.com/v6/businessEvent", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("options", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Praxedo_Send_Attachment_DEV.AttachmentManager.wsEntry[] options;
        
        public listAttachments() {
        }
        
        public listAttachments(string businessEventId, Praxedo_Send_Attachment_DEV.AttachmentManager.wsEntry[] options) {
            this.businessEventId = businessEventId;
            this.options = options;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listAttachmentsResponse", WrapperNamespace="http://ws.praxedo.com/v6/businessEvent", IsWrapped=true)]
    public partial class listAttachmentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.praxedo.com/v6/businessEvent", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Praxedo_Send_Attachment_DEV.AttachmentManager.attachmentsRequestResult @return;
        
        public listAttachmentsResponse() {
        }
        
        public listAttachmentsResponse(Praxedo_Send_Attachment_DEV.AttachmentManager.attachmentsRequestResult @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createAttachment", WrapperNamespace="http://ws.praxedo.com/v6/businessEvent", IsWrapped=true)]
    public partial class createAttachment {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.praxedo.com/v6/businessEvent", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Praxedo_Send_Attachment_DEV.AttachmentManager.attachment attachment;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.praxedo.com/v6/businessEvent", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] stream;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.praxedo.com/v6/businessEvent", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("options", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Praxedo_Send_Attachment_DEV.AttachmentManager.wsEntry[] options;
        
        public createAttachment() {
        }
        
        public createAttachment(Praxedo_Send_Attachment_DEV.AttachmentManager.attachment attachment, byte[] stream, Praxedo_Send_Attachment_DEV.AttachmentManager.wsEntry[] options) {
            this.attachment = attachment;
            this.stream = stream;
            this.options = options;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createAttachmentResponse", WrapperNamespace="http://ws.praxedo.com/v6/businessEvent", IsWrapped=true)]
    public partial class createAttachmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.praxedo.com/v6/businessEvent", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Praxedo_Send_Attachment_DEV.AttachmentManager.operationResult @return;
        
        public createAttachmentResponse() {
        }
        
        public createAttachmentResponse(Praxedo_Send_Attachment_DEV.AttachmentManager.operationResult @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BusinessEventAttachmentManagerChannel : Praxedo_Send_Attachment_DEV.AttachmentManager.BusinessEventAttachmentManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BusinessEventAttachmentManagerClient : System.ServiceModel.ClientBase<Praxedo_Send_Attachment_DEV.AttachmentManager.BusinessEventAttachmentManager>, Praxedo_Send_Attachment_DEV.AttachmentManager.BusinessEventAttachmentManager {
        
        public BusinessEventAttachmentManagerClient() {
        }
        
        public BusinessEventAttachmentManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BusinessEventAttachmentManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusinessEventAttachmentManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusinessEventAttachmentManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Praxedo_Send_Attachment_DEV.AttachmentManager.getAttachmentContentResponse Praxedo_Send_Attachment_DEV.AttachmentManager.BusinessEventAttachmentManager.getAttachmentContent(Praxedo_Send_Attachment_DEV.AttachmentManager.getAttachmentContent request) {
            return base.Channel.getAttachmentContent(request);
        }
        
        public Praxedo_Send_Attachment_DEV.AttachmentManager.attachmentContentOperationResult getAttachmentContent(string attachmentId, Praxedo_Send_Attachment_DEV.AttachmentManager.wsEntry[] options) {
            Praxedo_Send_Attachment_DEV.AttachmentManager.getAttachmentContent inValue = new Praxedo_Send_Attachment_DEV.AttachmentManager.getAttachmentContent();
            inValue.attachmentId = attachmentId;
            inValue.options = options;
            Praxedo_Send_Attachment_DEV.AttachmentManager.getAttachmentContentResponse retVal = ((Praxedo_Send_Attachment_DEV.AttachmentManager.BusinessEventAttachmentManager)(this)).getAttachmentContent(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Praxedo_Send_Attachment_DEV.AttachmentManager.getAttachmentContentResponse> Praxedo_Send_Attachment_DEV.AttachmentManager.BusinessEventAttachmentManager.getAttachmentContentAsync(Praxedo_Send_Attachment_DEV.AttachmentManager.getAttachmentContent request) {
            return base.Channel.getAttachmentContentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Praxedo_Send_Attachment_DEV.AttachmentManager.getAttachmentContentResponse> getAttachmentContentAsync(string attachmentId, Praxedo_Send_Attachment_DEV.AttachmentManager.wsEntry[] options) {
            Praxedo_Send_Attachment_DEV.AttachmentManager.getAttachmentContent inValue = new Praxedo_Send_Attachment_DEV.AttachmentManager.getAttachmentContent();
            inValue.attachmentId = attachmentId;
            inValue.options = options;
            return ((Praxedo_Send_Attachment_DEV.AttachmentManager.BusinessEventAttachmentManager)(this)).getAttachmentContentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Praxedo_Send_Attachment_DEV.AttachmentManager.deleteAttachmentResponse Praxedo_Send_Attachment_DEV.AttachmentManager.BusinessEventAttachmentManager.deleteAttachment(Praxedo_Send_Attachment_DEV.AttachmentManager.deleteAttachment request) {
            return base.Channel.deleteAttachment(request);
        }
        
        public Praxedo_Send_Attachment_DEV.AttachmentManager.operationResult deleteAttachment(Praxedo_Send_Attachment_DEV.AttachmentManager.attachment attachment, Praxedo_Send_Attachment_DEV.AttachmentManager.wsEntry[] options) {
            Praxedo_Send_Attachment_DEV.AttachmentManager.deleteAttachment inValue = new Praxedo_Send_Attachment_DEV.AttachmentManager.deleteAttachment();
            inValue.attachment = attachment;
            inValue.options = options;
            Praxedo_Send_Attachment_DEV.AttachmentManager.deleteAttachmentResponse retVal = ((Praxedo_Send_Attachment_DEV.AttachmentManager.BusinessEventAttachmentManager)(this)).deleteAttachment(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Praxedo_Send_Attachment_DEV.AttachmentManager.deleteAttachmentResponse> Praxedo_Send_Attachment_DEV.AttachmentManager.BusinessEventAttachmentManager.deleteAttachmentAsync(Praxedo_Send_Attachment_DEV.AttachmentManager.deleteAttachment request) {
            return base.Channel.deleteAttachmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Praxedo_Send_Attachment_DEV.AttachmentManager.deleteAttachmentResponse> deleteAttachmentAsync(Praxedo_Send_Attachment_DEV.AttachmentManager.attachment attachment, Praxedo_Send_Attachment_DEV.AttachmentManager.wsEntry[] options) {
            Praxedo_Send_Attachment_DEV.AttachmentManager.deleteAttachment inValue = new Praxedo_Send_Attachment_DEV.AttachmentManager.deleteAttachment();
            inValue.attachment = attachment;
            inValue.options = options;
            return ((Praxedo_Send_Attachment_DEV.AttachmentManager.BusinessEventAttachmentManager)(this)).deleteAttachmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Praxedo_Send_Attachment_DEV.AttachmentManager.listAttachmentsResponse Praxedo_Send_Attachment_DEV.AttachmentManager.BusinessEventAttachmentManager.listAttachments(Praxedo_Send_Attachment_DEV.AttachmentManager.listAttachments request) {
            return base.Channel.listAttachments(request);
        }
        
        public Praxedo_Send_Attachment_DEV.AttachmentManager.attachmentsRequestResult listAttachments(string businessEventId, Praxedo_Send_Attachment_DEV.AttachmentManager.wsEntry[] options) {
            Praxedo_Send_Attachment_DEV.AttachmentManager.listAttachments inValue = new Praxedo_Send_Attachment_DEV.AttachmentManager.listAttachments();
            inValue.businessEventId = businessEventId;
            inValue.options = options;
            Praxedo_Send_Attachment_DEV.AttachmentManager.listAttachmentsResponse retVal = ((Praxedo_Send_Attachment_DEV.AttachmentManager.BusinessEventAttachmentManager)(this)).listAttachments(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Praxedo_Send_Attachment_DEV.AttachmentManager.listAttachmentsResponse> Praxedo_Send_Attachment_DEV.AttachmentManager.BusinessEventAttachmentManager.listAttachmentsAsync(Praxedo_Send_Attachment_DEV.AttachmentManager.listAttachments request) {
            return base.Channel.listAttachmentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Praxedo_Send_Attachment_DEV.AttachmentManager.listAttachmentsResponse> listAttachmentsAsync(string businessEventId, Praxedo_Send_Attachment_DEV.AttachmentManager.wsEntry[] options) {
            Praxedo_Send_Attachment_DEV.AttachmentManager.listAttachments inValue = new Praxedo_Send_Attachment_DEV.AttachmentManager.listAttachments();
            inValue.businessEventId = businessEventId;
            inValue.options = options;
            return ((Praxedo_Send_Attachment_DEV.AttachmentManager.BusinessEventAttachmentManager)(this)).listAttachmentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Praxedo_Send_Attachment_DEV.AttachmentManager.createAttachmentResponse Praxedo_Send_Attachment_DEV.AttachmentManager.BusinessEventAttachmentManager.createAttachment(Praxedo_Send_Attachment_DEV.AttachmentManager.createAttachment request) {
            return base.Channel.createAttachment(request);
        }
        
        public Praxedo_Send_Attachment_DEV.AttachmentManager.operationResult createAttachment(Praxedo_Send_Attachment_DEV.AttachmentManager.attachment attachment, byte[] stream, Praxedo_Send_Attachment_DEV.AttachmentManager.wsEntry[] options) {
            Praxedo_Send_Attachment_DEV.AttachmentManager.createAttachment inValue = new Praxedo_Send_Attachment_DEV.AttachmentManager.createAttachment();
            inValue.attachment = attachment;
            inValue.stream = stream;
            inValue.options = options;
            Praxedo_Send_Attachment_DEV.AttachmentManager.createAttachmentResponse retVal = ((Praxedo_Send_Attachment_DEV.AttachmentManager.BusinessEventAttachmentManager)(this)).createAttachment(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Praxedo_Send_Attachment_DEV.AttachmentManager.createAttachmentResponse> Praxedo_Send_Attachment_DEV.AttachmentManager.BusinessEventAttachmentManager.createAttachmentAsync(Praxedo_Send_Attachment_DEV.AttachmentManager.createAttachment request) {
            return base.Channel.createAttachmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Praxedo_Send_Attachment_DEV.AttachmentManager.createAttachmentResponse> createAttachmentAsync(Praxedo_Send_Attachment_DEV.AttachmentManager.attachment attachment, byte[] stream, Praxedo_Send_Attachment_DEV.AttachmentManager.wsEntry[] options) {
            Praxedo_Send_Attachment_DEV.AttachmentManager.createAttachment inValue = new Praxedo_Send_Attachment_DEV.AttachmentManager.createAttachment();
            inValue.attachment = attachment;
            inValue.stream = stream;
            inValue.options = options;
            return ((Praxedo_Send_Attachment_DEV.AttachmentManager.BusinessEventAttachmentManager)(this)).createAttachmentAsync(inValue);
        }
    }
}
